apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: admission-controller-certificate
  namespace: swap-image
spec:
  secretName: admission-controller-certificate
  issuerRef:
    name: kubeadm-ca
    kind: ClusterIssuer
  commonName: swap-image.swap-image.svc.cluster.local
  dnsNames:
    - swap-image.swap-image.svc.cluster.local
    - swap-image.swap-image.svc